// Group the sales data by product and create an array of objects where each object contains the product name and the total revenue generated by that product.

const salesData = require('./exStatement');

function createObjProduct(name) {
  return salesData
    .filter(product => product.product === name)
    .reduce(
      (acc, cur) => ({
        product: name,
        quantity: acc.quantity + cur.quantity,
        price: acc.price + cur.quantity * cur.price
      }),
      { product: undefined, quantity: 0, price: 0 }
    );
}

function resumeSalesData(salesData) {
  const productNames = salesData
    .map(data => data.product)
    .reduce((acc, cur) => {
      if (!acc.includes(cur)) {
        acc.push(cur);
      }
      return acc;
    }, []);

  return productNames.map(product => createObjProduct(product));
}

console.log(resumeSalesData(salesData));
