// Calculate the total revenue generated by products that have a quantity sold greater than or equal to 10.

const salesData = require('./exStatement');

const revenueTen = salesData
  .filter(product => product.quantity >= 10)
  .reduce((acc, cur) => acc + cur.quantity * cur.price, 0);

console.log(revenueTen);
